name: Playwright Tests
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    schedule:
        - cron: '15 4,16 * * *'
jobs:
    playwright-test:
        name: GSK Playwright tests
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              working-directory: GSK/pw
              run: npm ci

            - name: Install Playwright Browsers
              working-directory: GSK/pw
              run: npx playwright install --with-deps chromium

            - name: Run Playwright tests
              working-directory: GSK/pw
              run: npx playwright test

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: GSK/pw/playwright-report/
                  retention-days: 30

    pirate-weather-test:
        name: Pirate Weather API tests
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              working-directory: PW
              run: npm ci

            - name: Install Playwright Browsers
              working-directory: PW
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              working-directory: PW
              env:
                  PW_TOKEN: ${{ secrets.PW_TOKEN }}
              run: npx playwright test

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: pirate-weather-report
                  path: PW/playwright-report/
                  retention-days: 30

    k6-tests:
        name: k6 ecommerce tests
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run k6 add to cart test
              uses: grafana/k6-action@v0.3.1
              with:
                  filename: k6/addToCart.js
              env:
                  BASE_URL: http://104.154.109.216:8000

            - name: Run k6 e2e test
              uses: grafana/k6-action@v0.3.1
              with:
                  filename: k6/e2e.js
              env:
                  BASE_URL: http://104.154.109.216:8000

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: k6-report
                  path: k6/reports
                  retention-days: 30
